# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: admissions.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='admissions.proto',
  package='admission_detail',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x61\x64missions.proto\x12\x10\x61\x64mission_detail\"\xeb\x01\n\tAdmission\x12\x12\n\nsubject_id\x18\x01 \x02(\x05\x12\x0f\n\x07hadm_id\x18\x02 \x02(\x05\x12\x14\n\x0ctimes_in_icu\x18\x03 \x02(\x05\x12\x0b\n\x03\x61ge\x18\x04 \x02(\x02\x12\x15\n\rdate_of_birth\x18\x05 \x02(\t\x12\x11\n\tadmittime\x18\x06 \x02(\t\x12\x11\n\tdischtime\x18\x07 \x02(\t\x12\x16\n\x0e\x61\x64mission_type\x18\x08 \x02(\t\x12\x11\n\tdiagnosis\x18\t \x02(\t\x12\x10\n\x08\x64\x62source\x18\n \x02(\t\x12\x1c\n\x14hospital_expire_flag\x18\x0b \x02(\x05\":\n\x07Subject\x12/\n\nadmissions\x18\x01 \x03(\x0b\x32\x1b.admission_detail.Admission')
)




_ADMISSION = _descriptor.Descriptor(
  name='Admission',
  full_name='admission_detail.Admission',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subject_id', full_name='admission_detail.Admission.subject_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hadm_id', full_name='admission_detail.Admission.hadm_id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='times_in_icu', full_name='admission_detail.Admission.times_in_icu', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='age', full_name='admission_detail.Admission.age', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date_of_birth', full_name='admission_detail.Admission.date_of_birth', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='admittime', full_name='admission_detail.Admission.admittime', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dischtime', full_name='admission_detail.Admission.dischtime', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='admission_type', full_name='admission_detail.Admission.admission_type', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='diagnosis', full_name='admission_detail.Admission.diagnosis', index=8,
      number=9, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dbsource', full_name='admission_detail.Admission.dbsource', index=9,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hospital_expire_flag', full_name='admission_detail.Admission.hospital_expire_flag', index=10,
      number=11, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=274,
)


_SUBJECT = _descriptor.Descriptor(
  name='Subject',
  full_name='admission_detail.Subject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='admissions', full_name='admission_detail.Subject.admissions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=334,
)

_SUBJECT.fields_by_name['admissions'].message_type = _ADMISSION
DESCRIPTOR.message_types_by_name['Admission'] = _ADMISSION
DESCRIPTOR.message_types_by_name['Subject'] = _SUBJECT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Admission = _reflection.GeneratedProtocolMessageType('Admission', (_message.Message,), dict(
  DESCRIPTOR = _ADMISSION,
  __module__ = 'admissions_pb2'
  # @@protoc_insertion_point(class_scope:admission_detail.Admission)
  ))
_sym_db.RegisterMessage(Admission)

Subject = _reflection.GeneratedProtocolMessageType('Subject', (_message.Message,), dict(
  DESCRIPTOR = _SUBJECT,
  __module__ = 'admissions_pb2'
  # @@protoc_insertion_point(class_scope:admission_detail.Subject)
  ))
_sym_db.RegisterMessage(Subject)


# @@protoc_insertion_point(module_scope)
