# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='events.proto',
  package='ALLEVENTS',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x65vents.proto\x12\tALLEVENTS\"~\n\x05\x45vent\x12\x12\n\nsubject_id\x18\x01 \x02(\x05\x12\x0f\n\x07hadm_id\x18\x02 \x02(\x05\x12\x11\n\tcharttime\x18\x03 \x02(\t\x12\x0c\n\x04\x63gid\x18\x04 \x01(\x02\x12\x0e\n\x06itemid\x18\x05 \x02(\x05\x12\r\n\x05value\x18\x06 \x01(\t\x12\x10\n\x08valueuom\x18\x07 \x01(\t\"+\n\x07\x45pisode\x12 \n\x06\x65vents\x18\x01 \x03(\x0b\x32\x10.ALLEVENTS.Event')
)




_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='ALLEVENTS.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subject_id', full_name='ALLEVENTS.Event.subject_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hadm_id', full_name='ALLEVENTS.Event.hadm_id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='charttime', full_name='ALLEVENTS.Event.charttime', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cgid', full_name='ALLEVENTS.Event.cgid', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='itemid', full_name='ALLEVENTS.Event.itemid', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ALLEVENTS.Event.value', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valueuom', full_name='ALLEVENTS.Event.valueuom', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=153,
)


_EPISODE = _descriptor.Descriptor(
  name='Episode',
  full_name='ALLEVENTS.Episode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='events', full_name='ALLEVENTS.Episode.events', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=198,
)

_EPISODE.fields_by_name['events'].message_type = _EVENT
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['Episode'] = _EPISODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
  DESCRIPTOR = _EVENT,
  __module__ = 'events_pb2'
  # @@protoc_insertion_point(class_scope:ALLEVENTS.Event)
  ))
_sym_db.RegisterMessage(Event)

Episode = _reflection.GeneratedProtocolMessageType('Episode', (_message.Message,), dict(
  DESCRIPTOR = _EPISODE,
  __module__ = 'events_pb2'
  # @@protoc_insertion_point(class_scope:ALLEVENTS.Episode)
  ))
_sym_db.RegisterMessage(Episode)


# @@protoc_insertion_point(module_scope)
